import type { CheckpointExam } from "@/types/content";

/**
 * A1 Checkpoint Exam — Ispit razine A1 (spec: curriculum/A1/checkpoint-exam.md).
 * Taken after Unit 8; soft gate that unlocks A2. Quiz sections (Slušanje,
 * Čitanje, Gramatika) are graded locally and set the pass/fail; the Govor
 * (speaking) section is AI-graded when a key is present and never blocks.
 *
 * Fresh items only (never copied from lessons/unit tests), drawn from A1
 * vocab/grammar (NOM→ACC→LOC→GEN, present + perfekt). Slide ids are unique
 * across the whole exam (s01–s38). NOT yet run through the native proofread
 * pass — run it before relying on the Croatian.
 */
export const a1checkpoint: CheckpointExam = {
  id: "a1checkpoint",
  levelId: "A1",
  title: "Ispit razine A1",
  titleEn: "A1 Checkpoint Exam",
  passPct: 70,
  afterUnitId: "a1u8",
  sections: [
    {
      title: "Slušanje (Listening)",
      slides: [
        // Dictation ×4 — type exactly what you hear.
        { id: "s01", type: "listen-type", tts: "Jučer sam čitao knjigu.", allowSlow: true,
          answers: ["Jučer sam čitao knjigu.", "Jučer sam čitao knjigu"],
          explanation: "Jučer sam čitao knjigu — Yesterday I read a book (perfekt: sam + čitao)." },
        { id: "s02", type: "listen-type", tts: "Ana se tušira ujutro.", allowSlow: true,
          answers: ["Ana se tušira ujutro.", "Ana se tušira ujutro"],
          explanation: "Ana se tušira ujutro — Ana showers in the morning (reflexive se in 2nd position)." },
        { id: "s03", type: "listen-type", tts: "Idem u kazalište.", allowSlow: true,
          answers: ["Idem u kazalište.", "Idem u kazalište"],
          explanation: "Idem u kazalište — I'm going to the theatre (u + ACC = direction)." },
        { id: "s04", type: "listen-type", tts: "Danas nemam novca.", allowSlow: true,
          answers: ["Danas nemam novca.", "Danas nemam novca"],
          explanation: "Danas nemam novca — Today I have no money (nema + genitive novca)." },
        // Number / price / time catch ×3.
        { id: "s05", type: "mc", prompt: "Listen: what time is it?", tts: "pola devet",
          options: ["8:30", "9:30", "9:00"], correctIndex: 0,
          explanation: "pola devet = half to nine = 8:30 (pola points to the NEXT hour)." },
        { id: "s06", type: "mc", prompt: "Listen: how much does it cost?", tts: "šezdeset sedam eura",
          options: ["67 €", "76 €", "60 €"], correctIndex: 0,
          explanation: "šezdeset sedam = 67." },
        { id: "s07", type: "mc", prompt: "Listen: what time is it?", tts: "tri sata",
          options: ["3:00", "2:00", "13:30"], correctIndex: 0,
          explanation: "tri sata = three o'clock (3:00)." },
        // Dialogue comprehension ×3.
        { id: "s08", type: "mc", prompt: "Listen. Where is this happening?",
          tts: "Dobar dan! Želim jednu kavu, molim. — Izvolite. — Hvala!",
          options: ["at a café", "at a train station", "at a doctor's"], correctIndex: 0,
          explanation: "Ordering a coffee → a café (kafić)." },
        { id: "s09", type: "mc", prompt: "Listen. What is the person looking for?",
          tts: "Oprostite, gdje je pošta? — Idite ravno, pa lijevo.",
          options: ["the post office", "the bank", "the museum"], correctIndex: 0,
          explanation: "»Gdje je pošta?« — they're looking for the post office." },
        { id: "s10", type: "mc", prompt: "Listen. How much is the t-shirt?",
          tts: "Koliko košta majica? — Dvadeset eura.",
          options: ["20 €", "12 €", "22 €"], correctIndex: 0,
          explanation: "»Dvadeset eura« = 20 euros." },
      ],
    },
    {
      title: "Čitanje (Reading)",
      slides: [
        // Passage (read once, answer 5) — a past-tense narrative, A1 vocab only.
        { id: "s11", type: "mc",
          prompt:
            "Read the text, then answer.\n\n»Prošli tjedan baka Marija je bila u Zagrebu. Ona je stara, ali jako voli grad. U subotu ujutro je posjetila Anu. Ana i baka su išle u muzej, a onda u park. Bilo je sunčano i toplo. Na tržnici je baka kupila lijepu žutu haljinu. Nije bila skupa. Navečer su gledale film u kinu. U nedjelju su jele ručak u restoranu — baka je jela ribu, a Ana juhu i salatu. Onda su pile kavu. Baka je bila jako sretna. Bilo je krasno.«\n\nGdje je bila baka Marija? (Where was grandma Marija?)",
          options: ["u Zagrebu", "u Splitu", "u Kanadi"], correctIndex: 0,
          explanation: "»baka Marija je bila u Zagrebu.«" },
        { id: "s12", type: "mc", prompt: "Same text: Koga je baka posjetila? (Whom did grandma visit?)",
          options: ["Anu", "Marka", "Toma"], correctIndex: 0,
          explanation: "»posjetila je Anu« (Ana → animate ACC Anu)." },
        { id: "s13", type: "mc", prompt: "Same text: Kakvo je bilo vrijeme? (What was the weather like?)",
          options: ["sunčano i toplo", "hladno i oblačno", "padala je kiša"], correctIndex: 0,
          explanation: "»Bilo je sunčano i toplo.«" },
        { id: "s14", type: "mc", prompt: "Same text: Što je baka kupila? (What did grandma buy?)",
          options: ["žutu haljinu", "crvene cipele", "plavu jaknu"], correctIndex: 0,
          explanation: "»kupila lijepu žutu haljinu.«" },
        { id: "s15", type: "mc", prompt: "Same text: Kakav je bio vikend za baku? (How was the weekend for grandma?)",
          options: ["krasno — bila je sretna", "dosadno", "grozno"], correctIndex: 0,
          explanation: "»Baka je bila jako sretna. Bilo je krasno.«" },
        // Dialogue-gap ×3 — pick the pragmatically right line.
        { id: "s16", type: "mc",
          prompt: "Choose the missing line:\n»Dobar dan! Izvolite?«\n»___«",
          options: ["Želim jednu kavu, molim.", "Doviđenja!", "Kako se zoveš?"], correctIndex: 0,
          explanation: "The waiter asks for your order → you order politely." },
        { id: "s17", type: "mc",
          prompt: "Choose the missing line:\n»Koliko košta ova majica?«\n»___«",
          options: ["Petnaest eura.", "U ponedjeljak.", "Idem u grad."], correctIndex: 0,
          explanation: "»Koliko košta?« asks a price → answer with a price." },
        { id: "s18", type: "mc",
          prompt: "Choose the missing line:\n»Dobar tek!«\n»___«",
          options: ["Hvala!", "Molim?", "Odakle si?"], correctIndex: 0,
          explanation: "A wish (»Dobar tek!«) is answered with »Hvala!«." },
      ],
    },
    {
      title: "Gramatika i vokabular (Grammar & vocabulary)",
      slides: [
        // biti + negation + questions
        { id: "s19", type: "fill", text: "___ li ti student?", blanks: [["Jesi"]],
          translation: "Are you a student? — (answer the question word)",
          explanation: "Jesi li…? — the question form of the 2sg jesam." },
        { id: "s20", type: "mc", prompt: "“He isn't a teacher.”",
          options: ["On nije učitelj.", "On ne je učitelj.", "On nema učitelj."], correctIndex: 0,
          explanation: "biti negates as nije (3sg), one word." },
        // gender + adjective agreement
        { id: "s21", type: "fill", text: "To je ___ mačka. (crn)", blanks: [["crna"]],
          translation: "That is a black cat.",
          explanation: "mačka is feminine → crna." },
        { id: "s22", type: "fill", text: "Moja majica je ___. (crven)", blanks: [["crvena"]],
          translation: "My t-shirt is red.",
          explanation: "majica is feminine → crvena." },
        // NOM / ACC plural
        { id: "s23", type: "fill", text: "Volim ___. (film, plural)", blanks: [["filmove"]],
          translation: "I love films.",
          explanation: "film → filmovi (NOM pl), ACC pl filmove." },
        { id: "s24", type: "fill", text: "Moje ___ su mlade. (sestra, plural)", blanks: [["sestre"]],
          translation: "My sisters are young.",
          explanation: "sestra → sestre (feminine NOM plural)." },
        // ACC singular incl. animate
        { id: "s25", type: "fill", text: "Čekam ___. (konobar)", blanks: [["konobara"]],
          translation: "I am waiting for the waiter.",
          explanation: "konobar is animate masculine → ACC konobara." },
        { id: "s26", type: "fill", text: "Pijem ___. (kava)", blanks: [["kavu"]],
          translation: "I am drinking coffee.",
          explanation: "kava is feminine → ACC kavu." },
        // present-tense verb classes
        { id: "s27", type: "fill", text: "Oni ___ vino. (piti)", blanks: [["piju"]],
          translation: "They drink wine.",
          explanation: "piti, -em class 3pl → piju." },
        { id: "s28", type: "fill", text: "Ja ___ ribu. (jesti)", blanks: [["jedem"]],
          translation: "I eat fish.",
          explanation: "jesti (irregular) 1sg → jedem." },
        // LOC vs ACC direction
        { id: "s29", type: "fill", text: "Idem ___. (grad — direction)", blanks: [["u grad"]],
          translation: "I am going to the city.",
          explanation: "Direction → u + ACC (grad unchanged)." },
        { id: "s30", type: "fill", text: "Živim ___. (Zagreb — location)", blanks: [["u Zagrebu"]],
          translation: "I live in Zagreb.",
          explanation: "Location → u + LOC: Zagreb → u Zagrebu." },
        // reflexive + time
        { id: "s31", type: "fill", text: "Ana ___ budi rano.", blanks: [["se"]],
          translation: "Ana wakes up early.",
          explanation: "buditi se is reflexive; se sits in 2nd position." },
        { id: "s32", type: "mc", prompt: "»Koliko je sati?« — 7:30 →",
          options: ["pola osam", "pola sedam", "sedam i pol"], correctIndex: 0,
          explanation: "pola osam = half to eight = 7:30." },
        // genitive: quantity, nema, brackets
        { id: "s33", type: "fill", text: "Nema ___. (kruh)", blanks: [["kruha"]],
          translation: "There is no bread.",
          explanation: "nema + genitive: kruh → kruha." },
        { id: "s34", type: "fill", text: "dva ___ (pivo)", blanks: [["piva"]],
          translation: "two beers",
          explanation: "2–4 take genitive singular: pivo → piva." },
        { id: "s35", type: "fill", text: "čaša ___ (voda)", blanks: [["vode"]],
          translation: "a glass of water",
          explanation: "Quantity + genitive: voda → vode." },
        // perfekt + clitic order
        { id: "s36", type: "fill", text: "Jučer ___ film. (ja, m — gledati)", blanks: [["sam gledao"]],
          translation: "Yesterday I watched a film.",
          explanation: "Perfekt = aux (sam) + past participle (gledao, masculine)." },
        { id: "s37", type: "fill", text: "Ana ___ haljinu. (kupiti)", blanks: [["je kupila"]],
          translation: "Ana bought a dress.",
          explanation: "kupiti → je kupila (feminine participle)." },
        { id: "s38", type: "mc", prompt: "Which sentence has the correct clitic order?",
          options: ["Zvao se Marko.", "Zvao je se Marko.", "Se zvao Marko."], correctIndex: 0,
          explanation: "Reflexive se in 2nd position; se + je → the je drops (Zvao se Marko)." },
      ],
    },
  ],
  speaking: {
    title: "Govor (Speaking)",
    prompts: [
      { id: "s01",
        task: "Introduce yourself in Croatian (4+ sentences): your name, where you are from, whether you are a student or your job, and one thing you like.",
        modelHr: "Zovem se Tom. Ja sam iz Kanade. Ja sam student. Volim kavu i volim hrvatski jezik.",
        rubricFocus: "biti + iz + genitive country (chunk) + volim + ACC" },
      { id: "s02",
        task: "Describe a café scene aloud: say who is there, what they are eating or drinking, and mention one price.",
        modelHr: "Ana i Marko su u kafiću. Ana pije kavu, a Marko jede kolač. Kava košta dva eura.",
        rubricFocus: "present-tense verbs + ACC objects + a price with genitive" },
      { id: "s03",
        task: "Answer the question »Što si radio / radila jučer?« (What did you do yesterday?) in 3+ past-tense sentences.",
        modelHr: "Jučer sam bio u gradu. Kupio sam majicu. Navečer sam gledao film.",
        rubricFocus: "perfekt (sam + participle), correct participle gender, clitic in 2nd position" },
      { id: "s04",
        task: "Roleplay: the shopkeeper says »Izvolite! Što tražite?« Respond appropriately — say what you are looking for and ask how much it costs.",
        modelHr: "Dobar dan! Tražim crvenu majicu. Koliko košta?",
        rubricFocus: "tražiti + ACC, colour agreement, Koliko košta? question" },
      { id: "s05",
        task: "Read this paragraph aloud, clearly: »Danas je lijep dan. Idem u grad. Prvo idem u muzej, a onda pijem kavu u kafiću. Jako volim grad.«",
        modelHr: "Danas je lijep dan. Idem u grad. Prvo idem u muzej, a onda pijem kavu u kafiću. Jako volim grad.",
        rubricFocus: "pronunciation and diacritic sounds (č, ž, j); fluency" },
    ],
  },
};
