import type { Lesson } from "@/types/content";

/**
 * A1 U2 L4 — Brojevi 1–20 (Numbers, counting only)
 * Spec: curriculum/A1/unit-2.md · grammar-reference §13.
 * Closed-set lesson: the number series counts as the vocab (listening-priority SRS).
 * Noun government after numbers is DEFERRED to Unit 7 — counting only here.
 */
export const a1u2l4: Lesson = {
  id: "a1u2l4",
  unitId: "a1u2",
  title: "Brojevi 1–20",
  titleEn: "Numbers 1–20",
  grammarTags: ["numbers-1-20"],
  estMinutes: 18,
  vocabPolicy: "closed-set",
  vocab: [
    { id: "a1u2.jedan", image: "/img/jedan.png", hr: "jedan", en: "one", pos: "num", icon: "1️⃣", exampleHr: "Jedan grad, jedna zemlja, jedno selo.", exampleEn: "One city, one country, one village." },
    { id: "a1u2.dva", image: "/img/dva.png", hr: "dva", en: "two", pos: "num", icon: "2️⃣", exampleHr: "Koliko je dva i dva? — Četiri.", exampleEn: "How much is two and two? — Four." },
    { id: "a1u2.tri", image: "/img/tri.png", hr: "tri", en: "three", pos: "num", icon: "3️⃣", exampleHr: "Jedan, dva, tri!", exampleEn: "One, two, three!" },
    { id: "a1u2.cetiri", image: "/img/cetiri.png", hr: "četiri", en: "four", pos: "num", icon: "4️⃣", exampleHr: "Koliko je dva i dva? — Četiri.", exampleEn: "How much is two and two? — Four." },
    { id: "a1u2.pet", image: "/img/pet.png", hr: "pet", en: "five", pos: "num", icon: "5️⃣", exampleHr: "Koliko je dva i tri? — Pet.", exampleEn: "How much is two and three? — Five." },
    { id: "a1u2.sest", image: "/img/sest.png", hr: "šest", en: "six", pos: "num", icon: "6️⃣", exampleHr: "Pet, šest, sedam.", exampleEn: "Five, six, seven." },
    { id: "a1u2.sedam", image: "/img/sedam.png", hr: "sedam", en: "seven", pos: "num", icon: "7️⃣", exampleHr: "To je broj sedam.", exampleEn: "That is number seven." },
    { id: "a1u2.osam", image: "/img/osam.png", hr: "osam", en: "eight", pos: "num", icon: "8️⃣", exampleHr: "Koliko je četiri i četiri? — Osam.", exampleEn: "How much is four and four? — Eight." },
    { id: "a1u2.devet", image: "/img/devet.png", hr: "devet", en: "nine", pos: "num", icon: "9️⃣", exampleHr: "Devet, deset!", exampleEn: "Nine, ten!" },
    { id: "a1u2.deset", image: "/img/deset.png", hr: "deset", en: "ten", pos: "num", icon: "🔟", exampleHr: "Koliko je pet i pet? — Deset.", exampleEn: "How much is five and five? — Ten." },
    { id: "a1u2.jedanaest", image: "/img/jedanaest.png", hr: "jedanaest", en: "eleven", pos: "num", icon: "🔢", exampleHr: "Deset, jedanaest, dvanaest.", exampleEn: "Ten, eleven, twelve." },
    { id: "a1u2.dvanaest", image: "/img/dvanaest.png", hr: "dvanaest", en: "twelve", pos: "num", icon: "🔢", exampleHr: "To je broj dvanaest.", exampleEn: "That is number twelve." },
    { id: "a1u2.trinaest", image: "/img/trinaest.png", hr: "trinaest", en: "thirteen", pos: "num", icon: "🔢", exampleHr: "To je broj trinaest.", exampleEn: "That is number thirteen." },
    { id: "a1u2.cetrnaest", image: "/img/cetrnaest.png", hr: "četrnaest", en: "fourteen", pos: "num", icon: "🔢", exampleHr: "Koliko je sedam i sedam? — Četrnaest.", exampleEn: "How much is seven and seven? — Fourteen." },
    { id: "a1u2.petnaest", image: "/img/petnaest.png", hr: "petnaest", en: "fifteen", pos: "num", icon: "🔢", exampleHr: "Koliko je deset i pet? — Petnaest.", exampleEn: "How much is ten and five? — Fifteen." },
    { id: "a1u2.sesnaest", image: "/img/sesnaest.png", hr: "šesnaest", en: "sixteen", pos: "num", icon: "🔢", exampleHr: "To je broj šesnaest.", exampleEn: "That is number sixteen." },
    { id: "a1u2.sedamnaest", image: "/img/sedamnaest.png", hr: "sedamnaest", en: "seventeen", pos: "num", icon: "🔢", exampleHr: "Sedamnaest, osamnaest, devetnaest.", exampleEn: "Seventeen, eighteen, nineteen." },
    { id: "a1u2.osamnaest", image: "/img/osamnaest.png", hr: "osamnaest", en: "eighteen", pos: "num", icon: "🔢", exampleHr: "Koliko je devet i devet? — Osamnaest.", exampleEn: "How much is nine and nine? — Eighteen." },
    { id: "a1u2.devetnaest", image: "/img/devetnaest.png", hr: "devetnaest", en: "nineteen", pos: "num", icon: "🔢", exampleHr: "Devetnaest, dvadeset!", exampleEn: "Nineteen, twenty!" },
    { id: "a1u2.dvadeset", image: "/img/dvadeset.png", hr: "dvadeset", en: "twenty", pos: "num", icon: "🔢", exampleHr: "Koliko je deset i deset? — Dvadeset.", exampleEn: "How much is ten and ten? — Twenty." },
    { id: "a1u2.koliko", image: "/img/koliko.png", hr: "koliko", en: "how much / how many", pos: "adv", icon: "❓", exampleHr: "Koliko je to?", exampleEn: "How much is that?", tags: ["question-word"] },
    { id: "a1u2.broj", image: "/img/broj.png", hr: "broj", en: "number", pos: "noun", gender: "m", icon: "🔢", exampleHr: "To je broj deset.", exampleEn: "That is number ten." },
  ],
  slides: [
    {
      id: "s01",
      type: "section",
      title: "Brojevi 1–20",
      subtitle: "Count to 20 and you can handle prices, ages and phone numbers.",
      emoji: "🔢",
      items: [
        { emoji: "🖐️", label: "1–10", hint: "hear them, type them" },
        { emoji: "🧩", label: "11–20: the -naest pattern", hint: "jedanaest, dvanaest…" },
        { emoji: "➕", label: "Croatian arithmetic", hint: "Koliko je dva i tri?" },
        { emoji: "🎤", label: "Count out loud", hint: "numbers are an ear skill" },
      ],
    },
    {
      id: "s02",
      type: "section",
      title: "Part 1 · 1–10",
      subtitle: "Ten little words you'll use every single day.",
      emoji: "🖐️",
      items: [
        { emoji: "📊", label: "The 1–10 grid", hint: "with TTS per number" },
        { emoji: "🎧", label: "Dictation ×3", hint: "sedam, devet, četiri" },
        { emoji: "👂", label: "Hear & pick", hint: "digits quiz" },
      ],
    },
    {
      id: "s03",
      type: "mc",
      review: true,
      prompt: "Warm-up from Unit 1 — listen: how is she feeling?",
      tts: "Odlično sam!",
      options: ["great", "tired", "not well"],
      correctIndex: 0,
      explanation: "odlično = excellent/great (Unit 1). Warmed up? Brojevi — numbers!",
    },
    {
      id: "s04",
      type: "teach",
      title: "1–10 — the foundation",
      body:
        "Here they are. Say each one out loud — stress on the **first** syllable, never the last.\n\n**jedan** is special: it agrees like an adjective — *jedan grad, jedna zemlja, jedno selo* (preview!). Everything else: just count.",
      table: {
        caption: "1–10",
        headers: ["#", "riječ (word)"],
        rows: [
          ["1", "jedan"],
          ["2", "dva"],
          ["3", "tri"],
          ["4", "četiri"],
          ["5", "pet"],
          ["6", "šest"],
          ["7", "sedam"],
          ["8", "osam"],
          ["9", "devet"],
          ["10", "deset"],
        ],
      },
      diagram: {
        kind: "callout",
        tone: "info",
        title: "jedan · jedna · jedno",
        text: "“One” copies the noun's gender like an adjective: jedan grad (m), jedna zemlja (f), jedno selo (n). A preview of L3's rule at work.",
      },
      examples: [
        { hr: "Jedan, dva, tri, četiri, pet.", en: "One, two, three, four, five." },
        { hr: "Šest, sedam, osam, devet, deset.", en: "Six, seven, eight, nine, ten." },
      ],
      ttsChips: ["jedan", "dva", "tri", "četiri", "pet", "šest", "sedam", "osam", "devet", "deset"],
    },
    {
      id: "s05",
      type: "listen-type",
      tts: "sedam",
      explanation: "sedam = 7. Stress on SE-dam.",
    },
    {
      id: "s06",
      type: "listen-type",
      tts: "devet",
      explanation: "devet = 9.",
    },
    {
      id: "s07",
      type: "listen-type",
      tts: "četiri",
      explanation: "četiri = 4 — mind the spelling: če-ti-ri, never “četri”.",
    },
    {
      id: "s08",
      type: "quiz-set",
      title: "Hear & pick the digit",
      items: [
        {
          prompt: "Listen: which number?",
          tts: "pet",
          options: ["5", "3", "10"],
          correctIndex: 0,
          explanation: "pet = 5.",
        },
        {
          prompt: "Listen: which number?",
          tts: "tri",
          options: ["3", "4", "13"],
          correctIndex: 0,
          explanation: "tri = 3 (trinaest would be 13).",
        },
        {
          prompt: "Listen: which number?",
          tts: "deset",
          options: ["10", "2", "6"],
          correctIndex: 0,
          explanation: "deset = 10.",
        },
      ],
    },
    {
      id: "s09",
      type: "section",
      title: "Part 2 · 11–20: the -naest pattern",
      subtitle: "The teens are just 1–9 wearing a -naest coat.",
      emoji: "🧩",
      items: [
        { emoji: "📊", label: "The 11–20 grid", hint: "jedanAEST, dvanAEST…" },
        { emoji: "👂", label: "Hear & pick the teens" },
        { emoji: "➕", label: "Croatian arithmetic", hint: "fill & spell" },
      ],
    },
    {
      id: "s10",
      type: "teach",
      title: "11–20: number + -naest",
      body:
        "Take 1–9, glue **-naest** on: jedan**aest**, dvan**aest**, trin**aest**… Two squeeze a little: četiri → **četrnaest** (the i drops), šest → **šesnaest** (the t drops).\n\n20 breaks the pattern: **dvadeset** (“two tens”).",
      table: {
        caption: "11–20",
        headers: ["#", "riječ (word)"],
        rows: [
          ["11", "jedanaest"],
          ["12", "dvanaest"],
          ["13", "trinaest"],
          ["14", "četrnaest ⚠️"],
          ["15", "petnaest"],
          ["16", "šesnaest ⚠️"],
          ["17", "sedamnaest"],
          ["18", "osamnaest"],
          ["19", "devetnaest"],
          ["20", "dvadeset"],
        ],
      },
      diagram: {
        kind: "callout",
        tone: "warn",
        title: "Counting only — for now",
        text: "No nouns after numbers yet! “Five coffees” needs a case pattern that arrives in Unit 7. Until then: count bare — jedan, dva, tri…",
      },
      examples: [
        { hr: "Jedanaest, dvanaest, trinaest.", en: "Eleven, twelve, thirteen." },
        { hr: "Koliko je deset i pet? — Petnaest.", en: "How much is ten and five? — Fifteen." },
      ],
      ttsChips: ["jedanaest", "dvanaest", "trinaest", "četrnaest", "petnaest", "šesnaest", "sedamnaest", "osamnaest", "devetnaest", "dvadeset"],
    },
    {
      id: "s11",
      type: "quiz-set",
      title: "Hear & pick: the teens",
      items: [
        {
          prompt: "Listen: which number?",
          tts: "šesnaest",
          options: ["16", "6", "17"],
          correctIndex: 0,
          explanation: "šesnaest = 16 (šest = 6).",
        },
        {
          prompt: "Listen: which number?",
          tts: "dvanaest",
          options: ["12", "2", "20"],
          correctIndex: 0,
          explanation: "dvanaest = 12 (dva = 2, dvadeset = 20).",
        },
        {
          prompt: "Listen: which number?",
          tts: "osamnaest",
          options: ["18", "8", "19"],
          correctIndex: 0,
          explanation: "osamnaest = 18.",
        },
      ],
    },
    {
      id: "s12",
      type: "fill",
      text: "Koliko je dva i tri? — ___.",
      blanks: [["Pet", "pet"]],
      translation: "How much is two and three? — Five.",
      explanation: "2 + 3 = 5 → pet.",
    },
    {
      id: "s13",
      type: "fill",
      text: "Deset i deset je ___.",
      blanks: [["dvadeset"]],
      translation: "Ten and ten is twenty.",
      explanation: "10 + 10 = 20 → dvadeset (“two tens”).",
    },
    {
      id: "s14",
      type: "type",
      prompt: "Spell out the number: 14",
      answers: ["četrnaest"],
      hint: "četiri loses its i in the teen form.",
      explanation: "14 = četrnaest (not “četirinaest”).",
    },
    {
      id: "s15",
      type: "type",
      prompt: "Spell out the number: 19",
      answers: ["devetnaest"],
      explanation: "19 = devetnaest (devet + naest).",
    },
    {
      id: "s16",
      type: "section",
      title: "Part 3 · Numbers in the wild",
      subtitle: "Phone numbers, questions, and counting out loud.",
      emoji: "📞",
      items: [
        { emoji: "📞", label: "Phone-number style", hint: "digit by digit" },
        { emoji: "❓", label: "Koliko je to?", hint: "the how-much question" },
        { emoji: "🔁", label: "Flashback quiz", hint: "da/ne + molim meet numbers" },
        { emoji: "🎤", label: "Count 1–10 aloud", hint: "then recap" },
      ],
    },
    {
      id: "s17",
      type: "example",
      title: "Numbers in real life",
      items: [
        { hr: "Broj je pet, devet, dva.", en: "The number is five, nine, two.", note: "phone numbers go digit by digit" },
        { hr: "Koliko je to? — Dvadeset.", en: "How much is that? — Twenty." },
        { hr: "To je broj trinaest.", en: "That is number thirteen." },
      ],
    },
    {
      id: "s18",
      type: "reorder",
      words: ["Koliko", "je", "to"],
      answers: ["Koliko je to?", "Koliko je to"],
      en: "How much is that?",
      explanation: "koliko = how much/many — your price-asking question from Unit 7 onward.",
    },
    {
      id: "s19",
      type: "quiz-set",
      review: true,
      title: "Flashback: numbers meet Unit 1 & L2",
      items: [
        {
          prompt: "Listen — you're being asked if that's a 5. It's a 6. Best answer?",
          tts: "Je li to pet?",
          options: ["Ne, šest!", "Da!", "Molim!"],
          correctIndex: 0,
          explanation: "Je li…? (L2 frame) + ne (Unit 1): Ne, šest!",
        },
        {
          prompt: "A clerk says: »Broj, molim!« What do they want?",
          options: ["a number, please", "a coffee, please", "your name"],
          correctIndex: 0,
          explanation: "broj = number, molim = please (Unit 1 courtesy).",
        },
        {
          prompt: "___ li to devetnaest? (Is that nineteen?)",
          options: ["Je", "Jesi", "Jesu"],
          correctIndex: 0,
          explanation: "to → 3rd person: Je li to…? (L2 question frame).",
        },
      ],
    },
    {
      id: "s20",
      type: "fill",
      review: true,
      text: "Je li to devet? — ___, to je deset.",
      blanks: [["Ne", "ne"]],
      translation: "Is that nine? — No, that's ten.",
      wordBank: ["Ne", "Da"],
      explanation: "ne = no (Unit 1) — it's a ten, not a nine.",
    },
    {
      id: "s21",
      type: "speak",
      targetHr: "jedan, dva, tri, četiri, pet, šest, sedam, osam, devet, deset",
      targetEn: "Count from 1 to 10 out loud.",
      phonetic: "YE-dan, dva, tree, CHE-ti-ri, pet, shest, SE-dam, O-sam, DE-vet, DE-set",
    },
    {
      id: "s22",
      type: "speak",
      targetHr: "pet, devet, dva, osam, jedan, sedam",
      targetEn: "Read this phone number aloud, digit by digit: 592 817.",
      phonetic: "pet, DE-vet, dva, O-sam, YE-dan, SE-dam",
    },
    {
      id: "s23",
      type: "recap",
      summary:
        "**1–20, counting only.** Teens = number + **-naest** (with two squeezes: **četrnaest**, **šesnaest**); 20 = **dvadeset**.\n\n**jedan/jedna/jedno** agrees like an adjective (preview). **Koliko je…?** asks how much.\n\n⚠️ No nouns after numbers yet — that pattern (and why it's *pet eura*) arrives in **Unit 7**.\n\nNumbers are an **ear skill**: your review deck will drill them listening-first.\n\nNext lesson: your first full verb — govorim hrvatski!",
      vocabIds: [
        "a1u2.jedan", "a1u2.dva", "a1u2.tri", "a1u2.cetiri", "a1u2.pet",
        "a1u2.sest", "a1u2.sedam", "a1u2.osam", "a1u2.devet", "a1u2.deset",
        "a1u2.jedanaest", "a1u2.dvanaest", "a1u2.trinaest", "a1u2.cetrnaest",
        "a1u2.petnaest", "a1u2.sesnaest", "a1u2.sedamnaest", "a1u2.osamnaest",
        "a1u2.devetnaest", "a1u2.dvadeset", "a1u2.koliko", "a1u2.broj",
      ],
    },
  ],
  // SRS cloze cards flagged by the unit spec (seeded on lesson completion).
  srsCloze: [
    { front: "The numbers 11–19 all end in -___.", answers: ["naest"], back: "jedanaest, dvanaest … devetnaest — all end in -naest." },
    { front: "Koliko je pet i pet? — ___. (10)", answers: ["deset"], back: "Pet i pet je deset.", tts: "deset" },
  ],
  notes: {
    inOneSentence: {
      en: "Numbers 1–20 are pure counting words for now — the teens just add -naest — and your job is to know them by EAR, not just by eye.",
      exampleHr: "Koliko je dva i tri? — Pet.",
    },
    deepDive: [
      {
        title: "The full grid 1–20",
        body:
          "Read each row aloud. Stress is never final: **JE**-dan, **SE**-dam, je-**DA**-naest… The teens are transparent once you see the glue: number + **-naest** (from “na deset”, on ten).\n\n**Spelling traps:** četiri (four syllables — never ~~četri~~) → **četrnaest** (here the i DOES drop); šest → **šesnaest** (the t drops); jedan + naest = **jedanaest** (one n, the a's meet).",
        table: {
          caption: "1–20 at a glance",
          headers: ["#", "word", "#", "word"],
          rows: [
            ["1", "jedan", "11", "jedanaest"],
            ["2", "dva", "12", "dvanaest"],
            ["3", "tri", "13", "trinaest"],
            ["4", "četiri", "14", "četrnaest ⚠️"],
            ["5", "pet", "15", "petnaest"],
            ["6", "šest", "16", "šesnaest ⚠️"],
            ["7", "sedam", "17", "sedamnaest"],
            ["8", "osam", "18", "osamnaest"],
            ["9", "devet", "19", "devetnaest"],
            ["10", "deset", "20", "dvadeset"],
          ],
        },
      },
      {
        title: "jedan, jedna, jedno — “one” is an adjective at heart",
        body:
          "*jedan* copies the noun's gender exactly like L3's adjectives: **jedan grad** (m) · **jedna zemlja** (f) · **jedno selo** (n). The other numbers don't change form when counting.\n\n⚠️ What about “two coffees, five students”? **Deferred.** Numbers 2+ demand special case forms from the noun — that whole machine is taught in **Unit 7**, after you know the genitive. Until then, this course will only ever ask you to count bare numbers. If you see *pet eura* in the wild, just note it and move on.",
        diagram: {
          kind: "callout",
          tone: "warn",
          title: "Counting only — nouns after numbers come in Unit 7",
          text: "Don't build “dva kava” or guess endings. The number+noun pattern needs the genitive (Unit 7). For now: count bare, always.",
        },
      },
      {
        title: "Numbers are an ear skill",
        body:
          "You'll meet numbers spoken — prices, phone numbers, times — far more often than written. That's why this lesson is dictation-heavy, and why your SRS cards for numbers prioritize the **listening** direction (hear → type). When reviewing, say every number aloud; when hearing one, picture the digit, not the English word.",
      },
    ],
    commonMistakes: [
      {
        wrong: "četri / četrinaest",
        right: "četiri / četrnaest",
        why: "Four keeps its i when alone (če-ti-ri) and drops it only in the teen form (četrnaest).",
      },
      {
        wrong: "šestnaest",
        right: "šesnaest",
        why: "šest drops its t before -naest.",
      },
      {
        wrong: "Stressing the last syllable, English-style (“jedanaEST”)",
        right: "je-DA-naest, PET-naest — stress never falls on the final syllable",
        why: "Croatian stress is never final. Where it lands varies by teen (je-DA-naest but PET-naest, TRI-naest) — copy the TTS, not an English habit.",
      },
      {
        wrong: "dva kava, pet kava (putting nouns after numbers)",
        right: "count bare for now: dva, pet — the number+noun pattern arrives in Unit 7",
        why: "Numbers 2+ govern special case forms you haven't learned yet; guessing builds bad habits.",
      },
    ],
    memoryHooks: [
      "-naest = “-teen”: jedanaest, dvanaest… exactly like eleven → nineteen.",
      "The two squeezers: čeTRnaest (i out), šeSnaest (t out).",
      "dvadeset = “two tens” — transparent arithmetic.",
      "jedan/jedna/jedno behaves like dobar/dobra/dobro — “one” is an adjective at heart.",
    ],
    connects: [
      { label: "Adjective agreement — jedan/jedna/jedno follows it (L3)", lessonId: "a1u2l3" },
      { label: "Yes/no frame around numbers: Je li to pet? (L2)", lessonId: "a1u2l2" },
      { label: "Numbers 2–4 & 5+ with nouns + prices (Unit 7)", lessonId: "a1u7l3" },
    ],
    selfCheck: [
      { q: "Count 1–5 in Croatian.", a: "jedan, dva, tri, četiri, pet." },
      { q: "How do you say 14 — and what's the spelling trap?", a: "četrnaest — četiri drops its i (never “četirinaest” or “četrinaest”)." },
      { q: "Koliko je devet i devet?", a: "Osamnaest (18)." },
      { q: "“One country” — with the right form of one?", a: "jedna zemlja (zemlja is feminine → jedna)." },
      { q: "Can you say “five coffees” yet? Why not?", a: "Not yet — nouns after numbers need the genitive patterns taught in Unit 7. For now, count bare." },
    ],
  },
};
