import type { Lesson } from "@/types/content";

/**
 * A1 U1 L4 — Kako se zoveš? (First questions, as fixed chunks)
 * Spec: curriculum/A1/unit-1.md · Grammar: grammar-reference.md §15.
 * zvati se stays an UNANALYZED CHUNK here (reflexives arrive in Unit 6).
 */
export const a1u1l4: Lesson = {
  id: "a1u1l4",
  unitId: "a1u1",
  title: "Kako se zoveš?",
  titleEn: "What's your name? (first questions)",
  grammarTags: ["questions", "chunks"],
  estMinutes: 17,
  vocab: [
    { id: "a1u1.kako", hr: "kako", en: "how", pos: "adv", icon: "❓", exampleHr: "Kako si?", exampleEn: "How are you?" },
    { id: "a1u1.tko", hr: "tko", en: "who", pos: "pron", icon: "👤", exampleHr: "Tko je to?", exampleEn: "Who is that?" },
    { id: "a1u1.sto", hr: "što", en: "what", pos: "pron", icon: "⬛", exampleHr: "Što je to?", exampleEn: "What is that?" },
    { id: "a1u1.ime", hr: "ime", en: "name", pos: "noun", gender: "n", icon: "🏷️", exampleHr: "Moje ime je Ana.", exampleEn: "My name is Ana." },
    { id: "a1u1.prijatelj", hr: "prijatelj", en: "friend (male)", pos: "noun", gender: "m", icon: "🤝", exampleHr: "Tom je prijatelj.", exampleEn: "Tom is a friend." },
    { id: "a1u1.prijateljica", hr: "prijateljica", en: "friend (female)", pos: "noun", gender: "f", icon: "👭", exampleHr: "Ana je prijateljica.", exampleEn: "Ana is a friend." },
    { id: "a1u1.gospodin", image: "/img/gospodin.png", hr: "gospodin", en: "Mr. / sir", pos: "noun", gender: "m", icon: "🎩", exampleHr: "To je gospodin Horvat.", exampleEn: "That is Mr. Horvat." },
    { id: "a1u1.gospoda", image: "/img/gospoda.png", hr: "gospođa", en: "Mrs. / madam", pos: "noun", gender: "f", icon: "👒", exampleHr: "To je gospođa Kovač.", exampleEn: "That is Mrs. Kovač." },
    { id: "a1u1.drago-mi-je", hr: "drago mi je", en: "nice to meet you", pos: "phrase", icon: "🤗", exampleHr: "Drago mi je!", exampleEn: "Nice to meet you!", tags: ["chunk"] },
    { id: "a1u1.zovem-se", hr: "zovem se", en: "my name is (lit. “I call myself”)", pos: "phrase", icon: "💬", exampleHr: "Zovem se Tom.", exampleEn: "My name is Tom.", tags: ["chunk"] },
  ],
  slides: [
    {
      id: "s01",
      type: "section",
      title: "Kako se zoveš?",
      subtitle: "Ask names, give yours, point at people and things — a full first conversation.",
      emoji: "🗣️",
      items: [
        { emoji: "💬", label: "The name exchange", hint: "Kako se zoveš? → Zovem se…" },
        { emoji: "👤", label: "tko & što", hint: "Who is that? What is that? → To je…" },
        { emoji: "🧩", label: "Drill the dialogue", hint: "fills, builds, dictation" },
        { emoji: "🎯", label: "Recap + 10 new flashcards" },
      ],
    },
    {
      id: "s02",
      type: "section",
      title: "Part 1 · The name exchange",
      subtitle: "One question, one answer, one smile — learned as fixed chunks.",
      emoji: "💬",
      items: [
        { emoji: "🎬", label: "The 4-beat first meeting", hint: "greet · ask · answer · Drago mi je!" },
        { emoji: "🏷️", label: "Kako se zoveš? → Zovem se…", hint: "plus the polite zovete" },
        { emoji: "🤗", label: "Drago mi je!", hint: "nice to meet you — use it whole" },
        { emoji: "🧩", label: "Quick checks" },
      ],
    },
    {
      id: "s03",
      type: "vocab-cards",
      title: "Meet today's words",
      vocabIds: [
        "a1u1.kako", "a1u1.tko", "a1u1.sto", "a1u1.ime", "a1u1.prijatelj",
        "a1u1.prijateljica", "a1u1.gospodin", "a1u1.gospoda", "a1u1.drago-mi-je", "a1u1.zovem-se",
      ],
    },
    {
      id: "s04",
      type: "teach",
      title: "Kako se zoveš? → Zovem se… (What's your name? → My name is…)",
      body:
        "Your first real conversation. Today's phrases are **chunks**: fixed wholes you use as-is. Why *se*? Why *zoveš*? Unit 6 will explain — for now, chunks are your friends.\n\nOne question, two registers — and its answer. You'll also hear **Moje ime je…** (“my name is…”, with *ime* = name). Answer with **Zovem se [ime]** or simply **Ja sam [ime]** — both perfect.",
      diagram: {
        kind: "flow",
        steps: [
          { label: "Greeting", emoji: "👋", example: "Dobar dan!" },
          { label: "Question", emoji: "❓", example: "Kako se zoveš?" },
          { label: "Name", emoji: "🏷️", example: "Zovem se Tom." },
          { label: "Nice to meet you!", emoji: "🤗", example: "Drago mi je!" },
        ],
      },
      table: {
        caption: "The name exchange — fixed chunks",
        headers: ["question", "to whom?", "answer"],
        rows: [
          ["Kako se zoveš?", "friend, peer (ti)", "Zovem se Tom. / Ja sam Tom."],
          ["Kako se zovete?", "stranger, elder (Vi)", "Zovem se Tom."],
          ["Kako si?", "friend (ti)", "Dobro sam!"],
          ["Kako ste?", "stranger, elder (Vi)", "Dobro sam, hvala."],
        ],
      },
      examples: [
        { hr: "Kako se zoveš?", en: "What's your name? (informal)" },
        { hr: "Zovem se Marko.", en: "My name is Marko.", note: "a chunk — don't take it apart yet" },
        { hr: "Ja sam Ana, a ti?", en: "I'm Ana — and you?", note: "a ti? = the bounce-back question" },
        { hr: "Drago mi je!", en: "Nice to meet you!" },
      ],
      ttsChips: ["Dobar dan!", "Ja sam Ana. Kako se zoveš?", "Kako se zovete?", "Zovem se Tom.", "Kako si?", "Drago mi je!"],
    },
    {
      id: "s05",
      type: "mc",
      prompt: "You're asking an older stranger their name. Which question?",
      options: ["Kako se zovete?", "Kako se zoveš?", "Tko je to?"],
      correctIndex: 0,
      explanation: "-te marks the polite/plural Vi form: Kako se zovete? (zoveš is for friends).",
    },
    {
      id: "s06",
      type: "type",
      prompt: "Answer as Ana would: »Kako se zoveš?« (What's your name?) — say “My name is Ana.”",
      answers: ["Zovem se Ana.", "Zovem se Ana", "zovem se Ana", "Ja sam Ana.", "Ja sam Ana"],
      hint: "Start with the chunk: Zovem se…",
      explanation: "Zovem se Ana. — or the equally good Ja sam Ana.",
    },
    {
      id: "s07",
      type: "type",
      prompt: "Translate: “Nice to meet you!”",
      answers: ["Drago mi je!", "Drago mi je", "drago mi je"],
      explanation: "Drago mi je — literally “it is dear to me”. Use it whole, smile included.",
    },
    {
      id: "s08",
      type: "fill",
      text: "Moje ___ je Ana.",
      blanks: [["ime"]],
      translation: "My name is Ana.",
      wordBank: ["ime", "kako", "tko"],
      explanation: "“moje ime” = my name — a set phrase for now (possessives arrive in Unit 3).",
    },
    {
      id: "s09",
      type: "section",
      title: "Part 2 · Who and what: tko & što",
      subtitle: "Two pointing questions, one answer pattern: To je…",
      emoji: "👤",
      items: [
        { emoji: "👤", label: "Tko je to? — people", hint: "To je Ana." },
        { emoji: "⬛", label: "Što je to? — things", hint: "To je kava." },
        { emoji: "🎩", label: "gospodin & gospođa", hint: "Mr. and Mrs." },
        { emoji: "🧲", label: "Match & check" },
      ],
    },
    {
      id: "s10",
      type: "teach",
      title: "Tko je to? Što je to? (Who / what is that?)",
      body:
        "Two pointing questions with one answer pattern: **To je…** (That is…).\n\n**tko** 👤 asks about *people*, **što** ⬛ asks about *things*. Titles for adults you don't know: **gospodin** (Mr.) and **gospođa** (Mrs.).",
      table: {
        caption: "Pointing questions",
        headers: ["question", "asks about…", "answer"],
        rows: [
          ["Tko je to? 👤", "people", "To je Ana. / To je gospodin Horvat."],
          ["Što je to? ⬛", "things", "To je kava. / To je čaj."],
        ],
      },
      examples: [
        { hr: "Tko je to? — To je Ana.", en: "Who is that? — That's Ana." },
        { hr: "Što je to? — To je kava.", en: "What is that? — That's coffee." },
        { hr: "To je gospodin Horvat.", en: "That is Mr. Horvat." },
        { hr: "Ana je prijateljica.", en: "Ana is a friend.", note: "prijatelj (m) → prijateljica (f), like student → studentica" },
      ],
      ttsChips: ["Tko je to?", "Što je to?", "To je Ana.", "To je kava."],
    },
    {
      id: "s11",
      type: "quiz-set",
      title: "Quick check: tko or što?",
      items: [
        {
          prompt: "You point at a THING and want to know what it is. Which question?",
          options: ["Što je to?", "Tko je to?", "Kako si?"],
          correctIndex: 0,
          explanation: "što = what (things); tko = who (people).",
        },
        {
          prompt: "Listen. What does the question mean?",
          tts: "Tko je to?",
          options: ["Who is that?", "What is that?", "How are you?"],
          correctIndex: 0,
          explanation: "tko = who. Tko je to? — Who is that?",
        },
        {
          prompt: "Ana is your female friend. Complete: Ana je tvoja _____ .",
          options: ["prijateljica", "prijatelj", "gospodin"],
          correctIndex: 0,
          explanation: "-ica makes the female pair: prijatelj → prijateljica (just like student → studentica).",
        },
      ],
    },
    {
      id: "s12",
      type: "match",
      prompt: "Match Croatian to English",
      pairs: [
        { a: "tko", b: "who" },
        { a: "što", b: "what" },
        { a: "kako", b: "how" },
        { a: "ime", b: "name" },
        { a: "gospodin", b: "Mr. / sir" },
        { a: "gospođa", b: "Mrs. / madam" },
      ],
    },
    {
      id: "s13",
      type: "section",
      title: "Part 3 · Drill the dialogue",
      subtitle: "Fills, builds and dictation — then say your whole intro out loud.",
      emoji: "🧩",
      items: [
        { emoji: "🧩", label: "Rebuild the chunks", hint: "Kako se zoveš? · Drago mi je" },
        { emoji: "🎧", label: "Dictation", hint: "Zovem se Marko." },
        { emoji: "🔁", label: "Lessons 1–3 review", hint: "greetings, škola, biti" },
        { emoji: "🎤", label: "Speak: Zovem se Tom. Drago mi je!" },
      ],
    },
    {
      id: "s14",
      type: "fill",
      text: "— Kako se ___? — ___ se Tom.",
      blanks: [["zoveš"], ["Zovem", "zovem"]],
      translation: "— What's your name? — My name is Tom.",
      wordBank: ["zoveš", "Zovem", "zovete"],
      explanation: "Question: Kako se zoveš? Answer: Zovem se Tom. The chunk flips zoveš → zovem.",
    },
    {
      id: "s15",
      type: "reorder",
      words: ["Kako", "se", "zoveš"],
      answers: ["Kako se zoveš", "Kako se zoveš?"],
      en: "What's your name?",
      explanation: "Kako se zoveš? — the word order of the chunk is fixed. Learn the melody.",
    },
    {
      id: "s16",
      type: "reorder",
      words: ["Drago", "mi", "je"],
      answers: ["Drago mi je", "Drago mi je!"],
      en: "Nice to meet you!",
      explanation: "Drago mi je — always this order (notice je hiding in second-ish position again…).",
    },
    {
      id: "s17",
      type: "listen-type",
      tts: "Zovem se Marko.",
      answers: ["Zovem se Marko", "zovem se Marko"],
      explanation: "Zovem se Marko. — My name is Marko.",
    },
    {
      id: "s18",
      type: "listen-type",
      tts: "Drago mi je.",
      answers: ["Drago mi je", "drago mi je"],
      explanation: "Drago mi je. — Nice to meet you.",
    },
    {
      id: "s19",
      type: "mc",
      prompt: "Marko asks you »Kako si?« (How are you?). What do you say?",
      options: ["Dobro sam!", "Zovem se Marko.", "To je kava."],
      correctIndex: 0,
      explanation: "Kako si? asks how you ARE → Dobro sam! (I'm well). Your name is a different question.",
    },
    {
      id: "s20",
      type: "fill",
      text: "— ___ je to? — To je gospođa Kovač.",
      blanks: [["Tko", "tko"]],
      translation: "— Who is that? — That's Mrs. Kovač.",
      wordBank: ["Tko", "Što", "Kako"],
      explanation: "A person → tko. Things → što.",
    },
    {
      id: "s21",
      type: "speak",
      targetHr: "Zovem se Tom. Drago mi je!",
      targetEn: "My name is Tom. Nice to meet you!",
      phonetic: "ZO-vem se TOM · DRA-go mi ye — now say it with your own name",
    },
    {
      id: "s22",
      type: "mc",
      review: true,
      prompt: "It's morning. Which greeting fits? (from Lesson 1)",
      options: ["Dobro jutro!", "Dobra večer!", "Dobar dan!"],
      correctIndex: 0,
      explanation: "Morning → Dobro jutro! (dan = midday hello, večer = evening).",
    },
    {
      id: "s23",
      type: "listen-type",
      review: true,
      tts: "škola",
      explanation: "škola — school, from Lesson 2. š = sh.",
    },
    {
      id: "s24",
      type: "fill",
      review: true,
      text: "Ona ___ studentica. (from Lesson 3)",
      blanks: [["je"]],
      translation: "She is a student.",
      wordBank: ["je", "sam", "su"],
      explanation: "ona → je. sam-si-JE-smo-ste-su.",
    },
    {
      id: "s25",
      type: "type",
      prompt: "Translate: “Who is that?”",
      answers: ["Tko je to?", "Tko je to", "tko je to"],
      explanation: "Tko je to? — tko for people. (Notice je in second position!)",
    },
    {
      id: "s26",
      type: "mc",
      prompt: "Listen. What does the question mean?",
      tts: "Što je to?",
      options: ["What is that?", "Who is that?", "What's your name?"],
      correctIndex: 0,
      explanation: "što = what. Što je to? — What is that?",
    },
    {
      id: "s27",
      type: "recap",
      summary:
        "**Your first questions, as chunks:** *Kako se zoveš/zovete?* → *Zovem se… / Ja sam…* · *Tko je to?* (people 👤) / *Što je to?* (things ⬛) → *To je…* · *Kako si/ste?* → *Dobro sam!* · seal it with **Drago mi je!**\n\nNext lesson: *molim* and *hvala* — politeness, ti vs Vi, and the grand Unit 1 review.",
      vocabIds: [
        "a1u1.kako", "a1u1.tko", "a1u1.sto", "a1u1.ime", "a1u1.prijatelj",
        "a1u1.prijateljica", "a1u1.gospodin", "a1u1.gospoda", "a1u1.drago-mi-je", "a1u1.zovem-se",
      ],
    },
  ],
  // SRS cloze cards flagged by the unit spec (seeded on lesson completion).
  srsCloze: [
    { front: "Kako si? — ___, hvala. (fine)", answers: ["dobro"], back: "Kako si? — Dobro, hvala.", tts: "Dobro, hvala." },
    { front: "___ je to? (who)", answers: ["tko"], back: "Tko je to? — To je Ana.", tts: "Tko je to?" },
    { front: "Kako ___? (how are you — to a friend)", answers: ["si"], back: "Kako si?", tts: "Kako si?" },
  ],
  notes: {
    inOneSentence: {
      en: "Croatian's first questions are fixed chunks — Kako se zoveš? · Tko je to? · Što je to? · Kako si? — learned whole now, analyzed later.",
      exampleHr: "Kako se zoveš? — Zovem se Ana. Drago mi je!",
    },
    deepDive: [
      {
        title: "Chunks, not grammar (yet)",
        body:
          "*Kako se zoveš?* literally means “How do you call yourself?” — the verb **zvati se** is reflexive, and reflexives are a Unit 6 topic. Until then, treat these as **unanalyzed wholes** with fixed word order:\n\n- **Kako se zoveš?** (ti) / **Kako se zovete?** (Vi) → **Zovem se…**\n- **Drago mi je** — “it is dear to me” → nice to meet you\n- **a ti? / a Vi?** — the bounce-back: *Ja sam Ana, a ti?*\n\nChunks are not cheating — natives learned them the same way, as children.",
        table: {
          caption: "Question → answer pairs",
          headers: ["question", "answer", "register"],
          rows: [
            ["Kako se zoveš?", "Zovem se… / Ja sam…", "ti"],
            ["Kako se zovete?", "Zovem se…", "Vi"],
            ["Kako si?", "Dobro sam! / Odlično!", "ti"],
            ["Kako ste?", "Dobro sam, hvala.", "Vi"],
            ["Tko je to?", "To je Ana / gospodin Horvat.", "—"],
            ["Što je to?", "To je kava / čaj.", "—"],
          ],
        },
      },
      {
        title: "The first-meeting script",
        body:
          "The whole dialogue is a four-beat dance — same order every time. Practise it until the melody is automatic.",
        diagram: {
          kind: "flow",
          steps: [
            { label: "Greeting", emoji: "👋", example: "Dobar dan! / Bok!" },
            { label: "Name question", emoji: "🏷️", example: "Ja sam Ana. Kako se zoveš?" },
            { label: "Answer", emoji: "💬", example: "Zovem se Tom." },
            { label: "Nice to meet you!", emoji: "🤗", example: "Drago mi je! — Također! (= likewise)" },
          ],
        },
      },
      {
        title: "tko vs što — people vs things",
        body:
          "**tko** = who (people 👤), **što** = what (things ⬛). Both answer with **To je…** — *To je Ana.* / *To je čaj.*\n\nMind the spelling: **tko** starts with t (English “who” tempts you to drop it). And *što* wears its š proudly — you earned that letter in Lesson 2.",
      },
    ],
    commonMistakes: [
      { wrong: "Kako zoveš ti? (word-by-word from “How call you?”)", right: "Kako se zoveš?", why: "The chunk has fixed word order and se is not optional — learn it whole." },
      { wrong: "Zovem se je Tom.", right: "Zovem se Tom.", why: "The answer chunk is Zovem se + name — no je anywhere in it." },
      { wrong: "Tko je to? — pointing at a coffee", right: "Što je to?", why: "tko is only for people; things take što." },
      { wrong: "Mi je drago. / Je mi drago.", right: "Drago mi je.", why: "Fixed chunk, fixed order — and the little words mi and je can't lead the phrase." },
    ],
    memoryHooks: [
      "Zoveš → zovem: the question ends in -š (you), the answer in -m (me) — flip the letter, flip the person.",
      "tko 👤 has a T for “Two eyes looking at you” — people; što ⬛ for stuff.",
      "Drago mi je ≈ “it's dear to me” — meeting you is a small gift.",
      "The -te in zovete = the polite plural you'll see everywhere with Vi (Kako ste? zovete… ).",
    ],
    connects: [
      { label: "Ja sam… (the answers these questions ask for)", lessonId: "a1u1l3" },
      { label: "Molim i hvala (courtesy + ti/Vi in full)", lessonId: "a1u1l5" },
    ],
    selfCheck: [
      { q: "Ask a peer their name; then ask an older stranger.", a: "Kako se zoveš? · Kako se zovete?" },
      { q: "Give two correct answers to “Kako se zoveš?”", a: "Zovem se [ime]. / Ja sam [ime]." },
      { q: "When do you use tko, and when što?", a: "tko for people (Tko je to? — To je Ana), što for things (Što je to? — To je kava)." },
      { q: "What does “Drago mi je” literally mean, and when do you say it?", a: "“It is dear to me” — say it when you meet someone, as “nice to meet you”." },
      { q: "Someone asks “Kako si?” — answer that you're well.", a: "Dobro sam! (hvala)." },
    ],
  },
};
