import type { Lesson } from "@/types/content";

/**
 * A1 U1 L5 — Molim i hvala (Courtesy, ti vs Vi, unit review)
 * Spec: curriculum/A1/unit-1.md · No new grammar machinery — chunks + register,
 * then an 8-slide review run sampling L1–L4 before the recap.
 */
export const a1u1l5: Lesson = {
  id: "a1u1l5",
  unitId: "a1u1",
  title: "Molim i hvala",
  titleEn: "Please and thank you (courtesy + unit review)",
  grammarTags: ["courtesy", "ti-vi-register", "unit-review"],
  estMinutes: 20,
  vocab: [
    { id: "a1u1.hvala", image: "/img/hvala.png", hr: "hvala", en: "thank you", pos: "interj", icon: "🙏", exampleHr: "Hvala! — Molim!", exampleEn: "Thank you! — You're welcome!", tags: ["courtesy"] },
    { id: "a1u1.molim", image: "/img/molim.png", hr: "molim", en: "please / you're welcome / pardon?", pos: "interj", icon: "🤲", exampleHr: "Kavu, molim.", exampleEn: "A coffee, please.", tags: ["courtesy"] },
    { id: "a1u1.oprostite", image: "/img/oprostite.png", hr: "oprostite", en: "excuse me / sorry (formal; oprosti to a friend)", pos: "interj", icon: "🙇", exampleHr: "Oprostite, gospodine!", exampleEn: "Excuse me, sir! (set phrase)", tags: ["courtesy"] },
    { id: "a1u1.izvolite", image: "/img/izvolite.png", hr: "izvolite", en: "here you go (formal; izvoli to a friend)", pos: "interj", icon: "🤝", exampleHr: "Izvolite, čaj!", exampleEn: "Here you go — tea!", tags: ["courtesy"] },
    { id: "a1u1.dovidenja", image: "/img/dovidenja.png", hr: "doviđenja", en: "goodbye (neutral/formal)", pos: "interj", icon: "👋", exampleHr: "Doviđenja, gospođo!", exampleEn: "Goodbye, madam! (set phrase)", tags: ["greeting"] },
    { id: "a1u1.bok", image: "/img/bok.png", hr: "bok", en: "hi / bye (very informal)", pos: "interj", icon: "😄", exampleHr: "Bok, Ana!", exampleEn: "Hi, Ana!", tags: ["greeting"] },
    { id: "a1u1.laku-noc", image: "/img/lakunoc.png", hr: "laku noć", en: "good night (farewell only)", pos: "phrase", icon: "🌙", exampleHr: "Laku noć!", exampleEn: "Good night!", tags: ["greeting", "chunk"] },
    { id: "a1u1.vidimo-se", image: "/img/vidimose.png", hr: "vidimo se", en: "see you", pos: "phrase", icon: "👀", exampleHr: "Vidimo se!", exampleEn: "See you!", tags: ["greeting", "chunk"] },
    { id: "a1u1.dobrodosli", image: "/img/dobrodosli.png", hr: "dobrodošli", en: "welcome", pos: "interj", icon: "🎉", exampleHr: "Dobrodošli u Hrvatsku!", exampleEn: "Welcome to Croatia! (set phrase)", tags: ["greeting"] },
    { id: "a1u1.odlicno", image: "/img/odlicno.png", hr: "odlično", en: "excellent / great", pos: "adv", icon: "🌟", exampleHr: "Kako si? — Odlično!", exampleEn: "How are you? — Excellent!" },
    { id: "a1u1.lose", image: "/img/lose.png", hr: "loše", en: "bad / poorly", pos: "adv", icon: "😞", exampleHr: "Loše, umoran sam.", exampleEn: "Badly — I'm tired." },
    { id: "a1u1.moze", image: "/img/moze.png", hr: "može", en: "OK / sure / works for me", pos: "interj", icon: "👌", exampleHr: "Kava? — Može!", exampleEn: "Coffee? — Sure!" },
  ],
  slides: [
    {
      id: "s01",
      type: "section",
      title: "Molim i hvala",
      subtitle: "Perfect manners, the ti/Vi switch — and the grand Unit 1 review.",
      emoji: "🙏",
      items: [
        { emoji: "☕", label: "Courtesy & the clock", hint: "hvala, molim, oprostite — and greetings by the hour" },
        { emoji: "🤝", label: "ti or Vi?", hint: "the switch that sets half your endings" },
        { emoji: "🏆", label: "The big unit review", hint: "everything from L1–L4, mixed" },
        { emoji: "🎯", label: "Recap + 12 new flashcards" },
      ],
    },
    {
      id: "s02",
      type: "section",
      title: "Part 1 · Courtesy & the clock",
      subtitle: "Greetings that follow the sun, and a whole café visit in six lines.",
      emoji: "☕",
      items: [
        { emoji: "🌅", label: "Greetings by the hour", hint: "Dobro jutro → Laku noć (leaving only!)" },
        { emoji: "☕", label: "The café script", hint: "Oprostite! Kavu, molim. Hvala! — Molim!" },
        { emoji: "🧩", label: "Quick checks" },
      ],
    },
    {
      id: "s03",
      type: "vocab-cards",
      title: "Meet today's words",
      vocabIds: [
        "a1u1.hvala", "a1u1.molim", "a1u1.oprostite", "a1u1.izvolite", "a1u1.dovidenja",
        "a1u1.bok", "a1u1.laku-noc", "a1u1.vidimo-se", "a1u1.dobrodosli", "a1u1.odlicno",
        "a1u1.lose", "a1u1.moze",
      ],
    },
    {
      id: "s04",
      type: "teach",
      title: "Half the language is politeness 🙏",
      body:
        "You can survive in Croatia with terrible grammar and perfect manners — not the other way around. Today: **hvala, molim, oprostite**, greetings for every hour, and the big social switch: **ti vs Vi**.\n\nThen the grand finale: a review run over everything in Unit 1.",
      diagram: {
        kind: "callout",
        tone: "info",
        title: "Today's win",
        text: "Order a coffee, thank the waiter, say goodbye — politely, and at the right time of day.",
      },
    },
    {
      id: "s05",
      type: "teach",
      title: "Greetings around the clock ☀️→🌙",
      body:
        "Greetings follow the sun. **Laku noć** is a *farewell only* — you say it leaving, never arriving.\n\nFor goodbyes any time: **doviđenja** (neutral/formal), **bok** or **ćao** (casual), **vidimo se** (see you!).",
      diagram: {
        kind: "flow",
        steps: [
          { label: "jutro (morning)", emoji: "🌅", example: "Dobro jutro!" },
          { label: "dan (day)", emoji: "🌤️", example: "Dobar dan!" },
          { label: "večer (evening)", emoji: "🌆", example: "Dobra večer!" },
          { label: "noć (night) — leaving", emoji: "🌙", example: "Laku noć!" },
        ],
      },
      ttsChips: ["Dobro jutro!", "Dobar dan!", "Dobra večer!", "Laku noć!", "Doviđenja!", "Vidimo se!"],
    },
    {
      id: "s06",
      type: "match",
      prompt: "Match the time of day to its greeting",
      pairs: [
        { a: "jutro 🌅", b: "Dobro jutro!" },
        { a: "dan 🌤️", b: "Dobar dan!" },
        { a: "večer 🌆", b: "Dobra večer!" },
        { a: "noć 🌙 (leaving)", b: "Laku noć!" },
      ],
    },
    {
      id: "s07",
      type: "teach",
      title: "At the café — a crash course in courtesy",
      body:
        "The whole courtesy system fits in one café visit. (*Kavu, molim* — why kav**u**? A chunk for now; Unit 4 explains the ending.)\n\n**molim** is a Swiss-army word: please, you're-welcome, and “pardon?” when you didn't hear.",
      table: {
        caption: "Café script",
        headers: ["situation", "you say…", "meaning"],
        rows: [
          ["getting attention", "Oprostite!", "Excuse me!"],
          ["ordering", "Kavu, molim. / Čaj, molim.", "Coffee/tea, please."],
          ["waiter agrees", "Može!", "Sure thing!"],
          ["waiter serves", "Izvolite!", "Here you go!"],
          ["you", "Hvala!", "Thank you!"],
          ["waiter", "Molim!", "You're welcome!"],
        ],
      },
      examples: [
        { hr: "Oprostite!", en: "Excuse me!", note: "to a stranger — formal -te" },
        { hr: "Kavu, molim.", en: "A coffee, please.", note: "chunk — don't analyze the -u yet" },
        { hr: "Može!", en: "Sure!", note: "the most useful little word in any café" },
        { hr: "Izvolite.", en: "Here you go.", note: "izvoli to a friend" },
        { hr: "Hvala! — Molim!", en: "Thanks! — You're welcome!", note: "molim bounces the thanks back" },
        { hr: "Doviđenja!", en: "Goodbye!", note: "do-vi-đe-nja — you can read every letter now" },
      ],
      ttsChips: ["Oprostite!", "Kavu, molim.", "Može!", "Izvolite!", "Hvala!", "Molim!"],
    },
    {
      id: "s08",
      type: "quiz-set",
      title: "Quick check: café manners",
      items: [
        {
          prompt: "The waiter hands you your coffee. What do you say?",
          options: ["Hvala!", "Oprostite!", "Doviđenja!"],
          correctIndex: 0,
          explanation: "Someone gives you something → Hvala! (thank you). He'll answer: Molim!",
        },
        {
          prompt: "You need the waiter's attention. What do you say?",
          options: ["Oprostite!", "Izvolite!", "Može!"],
          correctIndex: 0,
          explanation: "Oprostite! = excuse me — the polite attention-getter. (Izvolite is what HE says, serving you.)",
        },
      ],
    },
    {
      id: "s09",
      type: "section",
      title: "Part 2 · ti or Vi — then drill it",
      subtitle: "One social question decides your endings — then practice everything.",
      emoji: "🤝",
      items: [
        { emoji: "🤝", label: "The ti/Vi instinct", hint: "friends → ti · strangers, elders → Vi" },
        { emoji: "🧩", label: "Fills & translations", hint: "Dobra večer · laku noć · može" },
        { emoji: "🎧", label: "Dictation", hint: "Vidimo se! Dobrodošli!" },
        { emoji: "🎤", label: "Speak your full intro", hint: "Dobar dan! Ja sam Tom. Drago mi je!" },
      ],
    },
    {
      id: "s10",
      type: "teach",
      title: "ti or Vi? 🤝",
      body:
        "One question decides half your grammar endings: friend or stranger?\n\nRule of thumb: friends, family, kids → **ti**. Strangers, elders, waiters, officials → **Vi** (the -te forms). When unsure, start with Vi — Croatians will happily downgrade you to ti. Full treatment much later; this instinct is enough for now.",
      diagram: {
        kind: "contrast",
        left: {
          title: "ti — friends, family, kids",
          emoji: "😄",
          lines: [
            { hr: "Bok! Kako si?", en: "Hi! How are you?" },
            { hr: "Oprosti! / Izvoli!", en: "Sorry! / Here you go! (informal)" },
          ],
        },
        right: {
          title: "Vi — strangers, elders, waiters",
          emoji: "🎩",
          lines: [
            { hr: "Dobar dan! Kako ste?", en: "Good day! How are you?" },
            { hr: "Oprostite! / Izvolite!", en: "Excuse me! / Here you go! (formal)" },
          ],
        },
      },
    },
    {
      id: "s11",
      type: "quiz-set",
      title: "Quick check: ti or Vi?",
      items: [
        {
          prompt: "You're meeting Ana's grandmother. What do you ask?",
          options: ["Kako ste?", "Kako si?", "Bok, kako si?"],
          correctIndex: 0,
          explanation: "An elder you've just met → Vi forms: Kako ste? Save kako si for friends.",
        },
        {
          prompt: "You spot your friend Marko on the street. What do you say?",
          options: ["Bok!", "Doviđenja!", "Oprostite!"],
          correctIndex: 0,
          explanation: "A friend → informal bok! (doviđenja is a goodbye, oprostite is formal excuse-me).",
        },
      ],
    },
    {
      id: "s12",
      type: "fill",
      text: "Dobra ___! Kako ste?",
      blanks: [["večer"]],
      translation: "Good evening! How are you?",
      wordBank: ["večer", "jutro", "dan"],
      explanation: "Dobra + večer — večer is feminine, so dobrA (jutro takes dobro, dan takes dobar).",
    },
    {
      id: "s13",
      type: "fill",
      text: "— Kava? — ___!",
      blanks: [["Može", "može"]],
      translation: "— Coffee? — Sure!",
      wordBank: ["Može", "Hvala", "Loše"],
      explanation: "može = sure / OK / works for me — Croatia's favourite yes.",
    },
    {
      id: "s14",
      type: "type",
      prompt: "Translate: “thank you”",
      answers: ["hvala", "Hvala"],
      explanation: "hvala — and the polite reply is molim (you're welcome).",
    },
    {
      id: "s15",
      type: "fill",
      text: "Hvala! — ___!",
      blanks: [["Molim", "molim"]],
      translation: "“Thanks!” — “You're welcome!”",
      wordBank: ["Molim", "Hvala", "Oprostite"],
      explanation: "hvala ↔ molim is a ping-pong pair: every hvala earns a molim back.",
    },
    {
      id: "s16",
      type: "type",
      prompt: "Translate: “good night” (leaving!)",
      answers: ["laku noć", "Laku noć"],
      hint: "It's a farewell chunk with noć from Lesson 1.",
      explanation: "Laku noć! — only when leaving. Arriving in the evening → Dobra večer!",
    },
    {
      id: "s17",
      type: "listen-type",
      tts: "Vidimo se!",
      answers: ["Vidimo se", "vidimo se"],
      explanation: "Vidimo se! — See you! The casual goodbye between friends.",
    },
    {
      id: "s18",
      type: "listen-type",
      tts: "Dobrodošli!",
      answers: ["Dobrodošli", "dobrodošli"],
      explanation: "Dobrodošli! — Welcome! What Croatia will say to you at the door.",
    },
    {
      id: "s19",
      type: "listen-type",
      tts: "Izvolite!",
      answers: ["Izvolite", "izvolite"],
      explanation: "Izvolite — here you go / there you are (what you hear whenever anything is handed to you).",
    },
    {
      id: "s20",
      type: "mc",
      prompt: "Listen. Someone answers »Kako si?« (How are you?). What do they say?",
      tts: "Odlično!",
      options: ["Excellent!", "Badly.", "Sure!"],
      correctIndex: 0,
      explanation: "odlično = excellent/great — the upbeat answer to Kako si? (loše = badly, može = sure).",
    },
    {
      id: "s21",
      type: "fill",
      text: "Kako si? — ___, umoran sam.",
      blanks: [["Loše", "loše"]],
      translation: "How are you? — Badly, I'm tired.",
      wordBank: ["Loše", "Odlično", "Može"],
      explanation: "loše = badly — and umoran sam straight from Lesson 3 (clitic never first!).",
    },
    {
      id: "s22",
      type: "quiz-set",
      title: "Quick check: the courtesy kit",
      items: [
        {
          prompt: "You're leaving. Which one is “goodbye”?",
          options: ["doviđenja", "dobrodošli", "drago mi je"],
          correctIndex: 0,
          explanation: "doviđenja = goodbye (literally “until seeing”). dobrodošli = welcome, drago mi je = nice to meet you.",
        },
        {
          prompt: "»Kako si?« (How are you?) — you're having a GREAT day. You say:",
          options: ["Odlično!", "Loše.", "Ne."],
          correctIndex: 0,
          explanation: "odlično = excellent — the upbeat answer. (loše = badly, ne = no.)",
        },
        {
          prompt: "»Kako si?« — rough day. You say:",
          options: ["Loše.", "Odlično!", "Može."],
          correctIndex: 0,
          explanation: "loše = badly. (odlično = excellent, može = sure.)",
        },
      ],
    },
    {
      id: "s23",
      type: "speak",
      targetHr: "Dobar dan! Ja sam Tom. Drago mi je!",
      targetEn: "Good day! I'm Tom. Nice to meet you!",
      phonetic: "DO-bar DAN · ya sahm TOM · DRA-go mi ye — your full self-introduction",
    },
    {
      id: "s24",
      type: "section",
      title: "Part 3 · The big unit review",
      subtitle: "Eight rapid slides sampling everything from Lessons 1–4.",
      emoji: "🏆",
      items: [
        { emoji: "🔁", label: "L1–L2: words & letters", hint: "kava i voda, žena, škola" },
        { emoji: "🥁", label: "L3: biti forms", hint: "Mi smo prijatelji" },
        { emoji: "💬", label: "L4: the questions", hint: "Kako se zovete? Tko je to?" },
        { emoji: "🎯", label: "Recap — Unit 1 complete!" },
      ],
    },
    {
      id: "s25",
      type: "mc",
      review: true,
      prompt: "Listen. What does it mean? (Lesson 1)",
      tts: "kava i voda",
      options: ["coffee and water", "day and night", "tea and coffee"],
      correctIndex: 0,
      explanation: "kava = coffee, i = and, voda = water — your very first words.",
    },
    {
      id: "s26",
      type: "listen-type",
      review: true,
      tts: "žena",
      explanation: "žena — woman (Lesson 2). ž = the s in “measure”.",
    },
    {
      id: "s27",
      type: "type",
      review: true,
      prompt: "Write it in Croatian: “school” (Lesson 2)",
      answers: ["škola"],
      explanation: "škola — with š. Diacritics are letters, not decoration.",
    },
    {
      id: "s28",
      type: "fill",
      review: true,
      text: "Mi ___ prijatelji. (Lesson 3)",
      blanks: [["smo"]],
      translation: "We are friends.",
      wordBank: ["smo", "ste", "su"],
      explanation: "mi → smo. sam-si-je-SMO-ste-su.",
    },
    {
      id: "s29",
      type: "reorder",
      review: true,
      words: ["On", "je", "student"],
      answers: ["On je student", "On je student."],
      en: "He is a student.",
      explanation: "on → je (Lesson 3). And je is snuggled in second position, as always.",
    },
    {
      id: "s30",
      type: "reorder",
      review: true,
      words: ["Kako", "se", "zovete"],
      answers: ["Kako se zovete", "Kako se zovete?"],
      en: "What's your name? (formal)",
      explanation: "The Vi version of the name question (Lesson 4) — -te marks the formal register you met today.",
    },
    {
      id: "s31",
      type: "match",
      review: true,
      prompt: "The grand mix — match Croatian to English (L1–L4)",
      pairs: [
        { a: "jutro", b: "morning" },
        { a: "čaj", b: "tea" },
        { a: "ime", b: "name" },
        { a: "prijateljica", b: "friend (female)" },
        { a: "studentica", b: "student (female)" },
      ],
    },
    {
      id: "s32",
      type: "mc",
      review: true,
      prompt: "Listen. What does the question mean? (Lesson 4)",
      tts: "Tko je to?",
      options: ["Who is that?", "What is that?", "How are you?"],
      correctIndex: 0,
      explanation: "tko = who (people). Što je to? would ask about a thing.",
    },
    {
      id: "s33",
      type: "recap",
      summary:
        "**Courtesy kit:** hvala → molim · oprostite/oprosti · izvolite/izvoli · može. **Goodbyes:** doviđenja (formal), bok / vidimo se (casual), laku noć (leaving at night only). **Register:** friends → ti (Kako si?), strangers/elders → Vi (Kako ste?).\n\n**Unit 1 complete!** You can read anything, introduce yourself, ask names, and be impeccably polite. Next up: the story «Tom u Zagrebu» and the unit test — you're ready. Sretno (good luck)! 🎉",
      vocabIds: [
        "a1u1.hvala", "a1u1.molim", "a1u1.oprostite", "a1u1.izvolite", "a1u1.dovidenja",
        "a1u1.bok", "a1u1.laku-noc", "a1u1.vidimo-se", "a1u1.dobrodosli", "a1u1.odlicno",
        "a1u1.lose", "a1u1.moze",
      ],
    },
  ],
  // SRS cloze cards flagged by the unit spec (seeded on lesson completion).
  srsCloze: [
    { front: "___ mi je. (pleased to meet you)", answers: ["drago"], back: "Drago mi je.", tts: "Drago mi je." },
    { front: "Izvolite! — ___! (thank you)", answers: ["hvala"], back: "Izvolite! — Hvala!", tts: "Hvala" },
    { front: "___ noć! (good night)", answers: ["laku"], back: "Laku noć!", tts: "Laku noć" },
  ],
  notes: {
    inOneSentence: {
      en: "Croatian politeness runs on a small chunk kit — hvala, molim, oprostite, izvolite — greetings that follow the clock, and one social switch: ti for friends, Vi for everyone else.",
      exampleHr: "Kavu, molim. — Izvolite! — Hvala! — Molim!",
    },
    deepDive: [
      {
        title: "Greetings around the clock (and out the door)",
        body:
          "Arrivals follow the sun; **Laku noć** belongs to *departures only* (it wishes a light night — you can't wish that while walking in).\n\nGoodbyes any time: **doviđenja** (neutral/formal — literally “until seeing”), **bok/ćao** (casual), **vidimo se** (see you!).",
        diagram: {
          kind: "flow",
          steps: [
            { label: "jutro (morning)", emoji: "🌅", example: "Dobro jutro!" },
            { label: "dan (day)", emoji: "🌤️", example: "Dobar dan!" },
            { label: "večer (evening)", emoji: "🌆", example: "Dobra večer!" },
            { label: "noć (night) — leaving", emoji: "🌙", example: "Laku noć! Vidimo se!" },
          ],
        },
      },
      {
        title: "The courtesy words — one table",
        body:
          "**molim** is three words in one: *please* (Kavu, molim), *you're welcome* (Hvala! — Molim!), and *pardon?* (Molim? = say that again). **oprostite/izvolite** are the Vi forms; friends get **oprosti/izvoli** — the -te is the same formal ending as in *zovete* and *ste*.",
        table: {
          caption: "Courtesy kit",
          headers: ["word", "when", "en"],
          rows: [
            ["hvala", "receiving anything", "thank you"],
            ["molim", "asking / answering hvala / “pardon?”", "please / you're welcome / pardon?"],
            ["oprostite / oprosti", "attention or apology (Vi / ti)", "excuse me, sorry"],
            ["izvolite / izvoli", "handing something over (Vi / ti)", "here you go"],
            ["može", "agreeing to an offer", "sure, OK"],
            ["dobrodošli", "welcoming someone", "welcome"],
          ],
        },
      },
      {
        title: "ti vs Vi — the instinct",
        body:
          "Ask yourself one question: *would I be on first-name terms in English?* Yes → **ti**. No (stranger, elder, official, waiter) → **Vi**, which takes the **-te** verb forms: *Kako ste? Kako se zovete? Oprostite! Izvolite!*\n\nWhen unsure, open with Vi — being downgraded to ti is a compliment; the reverse is a faux pas. (The full grammar of Vi is a B2 topic; the instinct is an A1 essential.)",
        diagram: {
          kind: "callout",
          tone: "warn",
          title: "Bok is for buddies",
          text: "Don't greet officials, elders or shop staff with Bok! — that's Dobar dan territory. Bok/ćao only where ti feels right.",
        },
      },
    ],
    commonMistakes: [
      { wrong: "Dobar večer!", right: "Dobra večer!", why: "večer is feminine — dobrA. (dan is masculine → dobAR dan, jutro neuter → dobrO jutro.)" },
      { wrong: "Bok! to a stranger or official", right: "Dobar dan! (+ Vi forms)", why: "bok is strictly informal; strangers get the Vi register until invited otherwise." },
      { wrong: "Laku noć! when arriving at an evening party", right: "Dobra večer! (arriving) · Laku noć! (leaving)", why: "laku noć is a farewell wish — it ends the evening, it can't open it." },
      { wrong: "Answering “Hvala!” with “Hvala!”", right: "Hvala! — Molim!", why: "molim bounces the thanks back (you're welcome); it also means please and “pardon?”." },
    ],
    memoryHooks: [
      "hvala ↔ molim are a ping-pong pair: every hvala earns a molim back.",
      "The day arc rhymes with the sky: jutro 🌅 → dan 🌤️ → večer 🌆 → laku noć 🌙 (lights out = leaving).",
      "-te = polite: sTE, zoveTE, oprostiTE, izvoliTE — hear -te, think Vi.",
      "može = “can-do” — Croatia's one-word yes to any offer.",
    ],
    connects: [
      { label: "Kako se zoveš? (the questions your courtesy wraps around)", lessonId: "a1u1l4" },
      { label: "Slova i glasovi I (where dobro jutro was born)", lessonId: "a1u1l1" },
    ],
    selfCheck: [
      { q: "Greet someone at 9:00, at 14:00, and at 20:00.", a: "Dobro jutro! · Dobar dan! · Dobra večer!" },
      { q: "Order a coffee politely, and respond when it arrives.", a: "Kavu, molim. … Hvala! (waiter: Izvolite! / Molim!)" },
      { q: "Name three meanings of molim.", a: "please · you're welcome · pardon? (say it again)" },
      { q: "Ana's grandmother vs your friend Marko — how do you ask each “how are you?”", a: "Kako ste? (Vi, the grandmother) · Kako si? (ti, Marko)." },
      { q: "You're leaving a party at midnight. Two good goodbyes?", a: "Laku noć! · Doviđenja! (or casually: Bok! / Vidimo se!)" },
    ],
  },
};
