import type { CheckpointExam } from "@/types/content";

/**
 * A2 Checkpoint Exam (spec: curriculum/A2/checkpoint-exam.md).
 * 40 locally-graded quiz items (Slušanje 10 · Čitanje 10 · Gramatika 20)
 * + 4 AI-graded speaking prompts + 1 AI-graded guided writing task.
 *
 * Scoring policy matches the A1 checkpoint's documented deviation: the QUIZ
 * sections set pass/fail (≥70%); speaking and writing are AI-graded feedback
 * that never gates (key-optional per CLAUDE.md rule 4 — the spec's 75-pt
 * weighted total assumes an AI grader is always present, which we can't).
 *
 * Cloze distribution pinned to the spec's coverage map: future ×2 · DAT ×2 ·
 * modal ×1 · INS ×2 · GEN pl & numbers ×3 · comparatives ×3 · VOC ×1 ·
 * imperative ×2 · clitics ×2 · aspect ×2 = 20.
 *
 * ⚠️ DRAFT — authored autonomously; structurally validated, NOT yet proofread.
 */
export const a2checkpoint: CheckpointExam = {
  id: "a2checkpoint",
  levelId: "A2",
  title: "A2 završni ispit",
  titleEn: "A2 Checkpoint Exam",
  passPct: 70,
  afterUnitId: "a2u16",
  sections: [
    {
      title: "Slušanje (Listening)",
      slides: [
        {
          id: "s01",
          type: "mc",
          prompt: "Passage A — Ana phones Tom. Listen: what are they celebrating?",
          tts: "Ana zove Toma: »Tom, dođi na proslavu u subotu! Slavimo bakin rođendan.«",
          options: ["bakin rođendan", "Anin rođendan", "Novu godinu"],
          correctIndex: 0,
          explanation: "»Slavimo bakin rođendan.«",
        },
        {
          id: "s02",
          type: "mc",
          prompt: "Passage A continues. Kada je proslava? (When is the party?)",
          tts: "Proslava je petog lipnja u sedam sati, kod bake.",
          options: ["5.6.", "15.6.", "5.7."],
          correctIndex: 0,
          explanation: "petog lipnja = June 5th (dates in GEN).",
        },
        {
          id: "s03",
          type: "mc",
          prompt: "Passage A continues. What must Tom bring?",
          tts: "Donesi glazbu — i nemoj ništa govoriti baki, to je iznenađenje!",
          options: ["music", "a cake", "balloons"],
          correctIndex: 0,
          explanation: "»Donesi glazbu« — and keep the secret!",
        },
        {
          id: "s04",
          type: "mc",
          prompt: "Passage A ends. What will Tom do tomorrow?",
          tts: "Tom odgovara: »Doći ću sigurno! Javit ću ti se sutra.«",
          options: ["get in touch with Ana", "buy a present", "visit grandma"],
          correctIndex: 0,
          explanation: "»Javit ću ti se sutra.« — the future clitic cluster.",
        },
        {
          id: "s05",
          type: "mc",
          prompt: "Passage B — Marko's summer. What will he do in July?",
          tts: "Marko govori: »Ljeti ću raditi u restoranu — radit ću cijeli srpanj.«",
          options: ["work at the restaurant", "travel to Zagreb", "rest at the seaside"],
          correctIndex: 0,
          explanation: "»radit ću cijeli srpanj« — imperfective future, all month.",
        },
        {
          id: "s06",
          type: "mc",
          prompt: "Passage B continues. Kada će Marko putovati? (When will Marko travel?)",
          tts: "U kolovozu ću putovati. More je toplije od rijeke, a plaže su najljepše!",
          options: ["u kolovozu", "u srpnju", "u rujnu"],
          correctIndex: 0,
          explanation: "u kolovozu = in August.",
        },
        {
          id: "s07",
          type: "mc",
          prompt: "Passage B ends. Čime će Marko ići na plažu? (How will he get to the beach?)",
          tts: "Kupit ću novi bicikl i ići ću na plažu biciklom.",
          options: ["biciklom", "autom", "pješice"],
          correctIndex: 0,
          explanation: "biciklom — bare INS of means.",
        },
        {
          id: "s08",
          type: "listen-type",
          tts: "Javi mi se sutra!",
          explanation: "Javi mi se sutra! — get in touch with me tomorrow (DAT before se).",
        },
        {
          id: "s09",
          type: "listen-type",
          tts: "Na plaži ima puno ljudi.",
          explanation: "Na plaži ima puno ljudi — puno + GEN pl (irregular ljudi).",
        },
        {
          id: "s10",
          type: "listen-type",
          tts: "Putujem vlakom u Split.",
          explanation: "Putujem vlakom u Split — bare INS of transport.",
        },
      ],
    },
    {
      title: "Čitanje (Reading)",
      slides: [
        {
          id: "s11",
          type: "mc",
          prompt:
            "»Tomova godina: Tom je prošle godine počeo učiti hrvatski. Prvo je učio riječi i brojeve, a onda je počeo govoriti. U srpnju je putovao vlakom u Split — more je bilo toplije od rijeke i pio je kavu s Markom. Zimi je slavio bakin rođendan — proslava je bila iznenađenje! Baka mu je dala stari recept za tortu. Sada se Tom i Ana dopisuju svaki dan. Tom je odlučio: naučit će hrvatski i sljedeće godine preselit će se u Hrvatsku.«\n\nKada je Tom počeo učiti hrvatski? (When did Tom start learning Croatian?)",
          options: ["prošle godine", "prošlog ljeta", "sljedeće godine"],
          correctIndex: 0,
          explanation: "»Tom je prošle godine počeo učiti hrvatski.«",
        },
        {
          id: "s12",
          type: "mc",
          prompt: "Same text: Čime je Tom putovao u Split? (How did Tom travel to Split?)",
          options: ["vlakom", "autom", "avionom"],
          correctIndex: 0,
          explanation: "»putovao je vlakom u Split« — bare INS.",
        },
        {
          id: "s13",
          type: "mc",
          prompt: "Same text: Što je baka dala Tomu? (What did grandma give Tom?)",
          options: ["stari recept za tortu", "novu tortu", "poklon za rođendan"],
          correctIndex: 0,
          explanation: "»Baka mu je dala stari recept za tortu.« — mu = to him.",
        },
        {
          id: "s14",
          type: "mc",
          prompt: "Same text: Što Tom i Ana rade svaki dan? (What do Tom and Ana do every day?)",
          options: ["dopisuju se", "putuju", "slave rođendane"],
          correctIndex: 0,
          explanation: "»Tom i Ana se dopisuju svaki dan.«",
        },
        {
          id: "s15",
          type: "mc",
          prompt: "Same text: Što će Tom napraviti sljedeće godine? (What will Tom do next year?)",
          options: ["preselit će se u Hrvatsku", "završit će školu u Kanadi", "otvorit će restoran"],
          correctIndex: 0,
          explanation: "»sljedeće godine preselit će se u Hrvatsku.«",
        },
        {
          id: "s16",
          type: "mc",
          prompt:
            "»Pozivnica: Draga Ana! U subotu slavimo Markov rođendan. Proslava je desetog svibnja u osam sati, u restoranu kod mora. Dođi i donesi stare slike! — Odgovor: Poštovani gospodine Kovač, javljam Vam se zbog proslave. Doći ću u subotu. Srdačan pozdrav, Ana Horvat«\n\nKada je proslava? (When is the party?)",
          options: ["desetog svibnja u osam", "petog svibnja u sedam", "desetog lipnja u osam"],
          correctIndex: 0,
          explanation: "»Proslava je desetog svibnja u osam sati.«",
        },
        {
          id: "s17",
          type: "mc",
          prompt: "Same texts: Gdje je proslava? (Where is the party?)",
          options: ["u restoranu kod mora", "kod bake", "kod Ane"],
          correctIndex: 0,
          explanation: "»u restoranu kod mora« — kod + GEN.",
        },
        {
          id: "s18",
          type: "mc",
          prompt: "Same texts: Kako počinje formalni e-mail? (How does the formal e-mail open?)",
          options: ["Poštovani gospodine Kovač,", "Draga Ana!", "Halo, gospodine!"],
          correctIndex: 0,
          explanation: "Formal = Poštovani + title + surname (halo is phone-only!).",
        },
        {
          id: "s19",
          type: "mc",
          prompt: "The letter is FINISHED and sent. Which sentence says that?",
          options: ["Napisao je pismo.", "Pisao je pismo.", "Piše pismo."],
          correctIndex: 0,
          explanation: "napisao — perfective: done, result exists.",
        },
        {
          id: "s20",
          type: "mc",
          prompt: "She gave it to him. Which order is correct?",
          options: ["Dala mu ga je.", "Dala je mu ga.", "Dala ga mu je."],
          correctIndex: 0,
          explanation: "DAT → ACC → je-caboose.",
        },
      ],
    },
    {
      title: "Gramatika i riječi (Grammar & vocab)",
      slides: [
        {
          id: "s21",
          type: "fill",
          text: "Sutra ___ ti poslati odgovor.",
          blanks: [["ću", "cu"]],
          translation: "I'll send you the answer tomorrow.",
          explanation: "Future aux ću, second position.",
        },
        {
          id: "s22",
          type: "fill",
          text: "(pisati) »___ ću ti sutra.«",
          blanks: [["Pisat", "pisat"]],
          translation: "I'll write to you tomorrow.",
          explanation: "pisat ću — the -ti drops its i.",
        },
        {
          id: "s23",
          type: "fill",
          text: "Šaljem ___ poruku. (mama)",
          blanks: [["mami"]],
          translation: "I'm sending mum a message.",
          explanation: "Receiver → DAT mami.",
        },
        {
          id: "s24",
          type: "mc",
          prompt: "Sviđa ___ se objava.",
          options: ["mi", "me", "ja"],
          correctIndex: 0,
          explanation: "sviđati se + DAT: mi (before se).",
        },
        {
          id: "s25",
          type: "mc",
          prompt: "Moraš ___ na proslavu!",
          options: ["doći", "dođi", "dođeš"],
          correctIndex: 0,
          explanation: "Modal + infinitive: moraš doći.",
        },
        {
          id: "s26",
          type: "fill",
          text: "Idem u grad ___. (auto)",
          blanks: [["autom"]],
          translation: "I'm going to town by car.",
          explanation: "Means of transport = bare INS: autom (no s!).",
        },
        {
          id: "s27",
          type: "fill",
          text: "Razgovaram ___ šeficom. (s or sa?)",
          blanks: [["sa"]],
          translation: "I'm talking with the boss.",
          explanation: "sa before š: sa šeficom.",
        },
        {
          id: "s28",
          type: "fill",
          text: "Baka ima pet ___. (mačka)",
          blanks: [["mačaka", "macaka"]],
          translation: "Grandma has five cats.",
          explanation: "5+ → GEN pl with the inserted a: mačaka.",
        },
        {
          id: "s29",
          type: "fill",
          text: "U parku nema ___. (pas — plural!)",
          blanks: [["pasa"]],
          translation: "There are no dogs in the park.",
          explanation: "GEN pl — the fleeting a returns: pasa.",
        },
        {
          id: "s30",
          type: "mc",
          prompt: "dva ___ (pas)",
          options: ["psa", "pasa", "pas"],
          correctIndex: 0,
          explanation: "2–4 → GEN sg: dva psa.",
        },
        {
          id: "s31",
          type: "mc",
          prompt: "Zagreb je veći ___ Splita.",
          options: ["od", "nego", "iz"],
          correctIndex: 0,
          explanation: "od + GEN (nego would need NOM: nego Split).",
        },
        {
          id: "s32",
          type: "fill",
          text: "Zima je ___ od jeseni. (hladan)",
          blanks: [["hladnija"]],
          translation: "Winter is colder than autumn.",
          explanation: "Comparative, feminine: hladnija.",
        },
        {
          id: "s33",
          type: "fill",
          text: "Dinara je ___ planina u Hrvatskoj. (visok — superlative)",
          blanks: [["najviša", "najvisa"]],
          translation: "Dinara is the highest mountain in Croatia.",
          explanation: "naj- + viša = najviša.",
        },
        {
          id: "s34",
          type: "fill",
          text: "___, dođi na proslavu! (Ivan)",
          blanks: [["Ivane", "ivane"]],
          translation: "Ivan, come to the party!",
          explanation: "VOC -e: Ivane!",
        },
        {
          id: "s35",
          type: "mc",
          prompt: "Nemoj ___ tortu!",
          options: ["jesti", "jedi", "jedite"],
          correctIndex: 0,
          explanation: "nemoj + INFINITIVE: nemoj jesti.",
        },
        {
          id: "s36",
          type: "fill",
          text: "doći, ti-form: »___ na proslavu!«",
          blanks: [["Dođi", "dođi", "Dodi"]],
          translation: "Come to the party!",
          explanation: "The rebel four: dođi!",
        },
        {
          id: "s37",
          type: "reorder",
          words: ["Dala", "mu", "ga", "je"],
          answers: ["Dala mu ga je.", "Dala mu ga je"],
          en: "She gave it to him.",
          explanation: "DAT → ACC → je last.",
        },
        {
          id: "s38",
          type: "fill",
          text: "Vidiš li Anu? — Ne, ne vidim ___.",
          blanks: [["je"]],
          translation: "Do you see Ana? — No, I don't see her.",
          explanation: "her → ACC clitic je.",
        },
        {
          id: "s39",
          type: "mc",
          prompt: "Jučer sam ___ knjigu cijeli dan.",
          options: ["čitao", "pročitao", "čitam"],
          correctIndex: 0,
          explanation: "cijeli dan (duration) → imperfective čitao.",
        },
        {
          id: "s40",
          type: "mc",
          prompt: "»___ plan do petka.« (it will exist by Friday!)",
          options: ["Napravit ću", "Radit ću", "Napravim"],
          correctIndex: 0,
          explanation: "Deadline + result → perfective future: napravit ću.",
        },
      ],
    },
  ],
  speaking: {
    title: "Govor (Speaking)",
    prompts: [
      {
        id: "s41",
        task: "Tell your story: where you were born, where you grew up, what you finished. (Ispričaj svoju priču: gdje si se rodio/rodila, gdje si odrastao/odrasla, što si završio/završila.) Aim for 4+ sentences.",
        modelHr: "Rodio sam se u Kanadi. Odrastao sam u Torontu. Završio sam školu. Sada živim u Zagrebu i učim hrvatski.",
        rubricFocus: "biography frames with correct participle gender and aspect (rodio se, odrastao, završio)",
      },
      {
        id: "s42",
        task: "What will you do next year? Say three plans. (Što ćeš raditi sljedeće godine? Reci tri plana.)",
        modelHr: "Sljedeće godine preselit ću se u Hrvatsku. Naučit ću hrvatski. Radit ću kao učitelj.",
        rubricFocus: "future I with sensible aspect choices (radit ću vs napravit ću / naučit ću)",
      },
      {
        id: "s43",
        task: "Compare summer and winter — which is better and why? (Usporedi ljeto i zimu — što je bolje i zašto?)",
        modelHr: "Ljeto je bolje od zime. Ljeti je toplije i ima puno sunca. Zimi je hladno, ali more je najljepše ljeti.",
        rubricFocus: "comparatives and superlatives with od/nego, plus puno + GEN",
      },
      {
        id: "s44",
        task: "Leave a voicemail inviting a friend to a party: greet them by name, say when the party is, and what to bring. (Pozovi prijatelja na proslavu: pozdravi ga, reci kada je proslava i što treba donijeti.)",
        modelHr: "Ana, dođi na proslavu! Proslava je petog svibnja u sedam sati. Donesi glazbu i javi mi se!",
        rubricFocus: "vocative + imperative + a date in GEN + a clitic (javi mi se)",
      },
    ],
  },
  writing: {
    title: "Pisanje (Writing)",
    task: "Write Ana an e-mail (40–60 words) inviting her to your celebration: say WHEN it is (the date — in the genitive!), WHAT you're celebrating, and what she should bring. Open and close the e-mail properly. (Napiši e-mail Ani. Pozovi je na svoju proslavu: napiši kada je proslava, što slavite i što Ana treba donijeti. Počni i završi e-mail kako treba.)",
    minWords: 40,
    maxWords: 60,
    modelHr:
      "Draga Ana!\nU subotu slavim rođendan i pozivam te na proslavu. Proslava je petog svibnja u sedam sati, kod mene. Dođi i donesi glazbu — bit će puno ljudi i puno torte! Nemoj ništa govoriti Marku, to je iznenađenje. Javi mi se!\nPozdrav,\nTom",
    rubricFocus: "e-mail frame (opening/closing), a date in GEN, an imperative or nemoj, and at least one clitic (pozivam te / javi mi se)",
  },
};
